# Jekyll configuration for Open SDG platform

create_config_forms:
    layout: config-builder

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
# Recommended: set this to a particular "release" of Open SDG. For example:
remote_theme: brockfanning/open-sdg@series-unit-field-revamp


# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
url: ""
baseurl: "/site"

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
